### ISSUE TITLE
Allow bringing personal environment via SSH

### ISSUE THREAD

**Issue by schlomo** [ImmobilienScout24/c-bastion#3]
Implement [SSH with Personal Environment
](http://blog.schlomo.schapiro.org/2014/02/ssh-with-personal-environment.html) to allow users to customize their shell environment on c-bastion.

![](https://docs.google.com/drawings/d/1nUEAGLu0qUclJF5iasyKgZp2Ft7WwV-fHCbZVQVvkhg/pub?w=799&amp;h=505)

**Comment by esc** [comment]
We will be unable to implement this in a reasonable time-frame, please consider submitting a pull-request instead.

**Comment by schlomo** [comment]
Implemented with f1e2cb3f48ac46c575fabe732adb88fb3d2150f8
